// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjTuDI-6NQ0yjwCErdkXVLjBjCKhqxNMc',
    appId: '1:526149271468:web:8e3d76dbe94df80460c409',
    messagingSenderId: '526149271468',
    projectId: 'ogincpratibha',
    authDomain: 'ogincpratibha.firebaseapp.com',
    storageBucket: 'ogincpratibha.appspot.com',
    measurementId: 'G-7RQVPC9QZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-WeVKcXiAj7OR9Y-WKKfoHemjKCFkMFM',
    appId: '1:526149271468:android:33d50783f365cc9560c409',
    messagingSenderId: '526149271468',
    projectId: 'ogincpratibha',
    storageBucket: 'ogincpratibha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaSnPJa_1TZOMvANqMOMFIRH0DPNych-o',
    appId: '1:526149271468:ios:19bdbceefb50bf9a60c409',
    messagingSenderId: '526149271468',
    projectId: 'ogincpratibha',
    storageBucket: 'ogincpratibha.appspot.com',
    iosBundleId: 'com.example.congressadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaSnPJa_1TZOMvANqMOMFIRH0DPNych-o',
    appId: '1:526149271468:ios:0334c278daba1edd60c409',
    messagingSenderId: '526149271468',
    projectId: 'ogincpratibha',
    storageBucket: 'ogincpratibha.appspot.com',
    iosBundleId: 'com.example.congressadmin.RunnerTests',
  );
}
